server:
  port: 80
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oacheck
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 40
      max-wait: 60
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # oracle为true,mysql建议false   #PSCache 相关
      pool-prepared-statements: false
      # oracle可设置100,mysql建议-1 #PSCache 相关
      max-pool-prepared-statement-per-connection-size: -1
      use-global-data-source-stat: true
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 0


mybatis:
  type-aliases-package: com.mingo.oacheck.dao
  mapper-locations:
    - classpath*:mapper/*.xml